from contextlib import asynccontextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Annotated

from fastapi import Depends, FastAPI, HTTPException, Query
from sqlmodel import Field, Session, SQLModel, create_engine, select

# ---------- Models ----------

class Service(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)  # generated by the db
    name: str
    service_time: int  # average minutes per customer

class Ticket(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)  # generated by the db
    service_id: int = Field(foreign_key="service.id")
    status: str = "waiting" # waiting/serving/done
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

class Counter(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)  # generated by the db
    name: str

class Counter_Service(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)  # generated by the db
    counter_id: int = Field(foreign_key="counter.id")
    service_id: int = Field(foreign_key="service.id")

# ---------- DB setup ----------

DB_PATH = Path(__file__).resolve().parent.parent / "OQM.db"  # backend/OQM.db

engine = create_engine(
    f"sqlite:///{DB_PATH}",
    connect_args={"check_same_thread": False},  # needed for SQLite + FastAPI
)


def get_session():
    with Session(engine) as session:
        yield session


SessionDep = Annotated[Session, Depends(get_session)]


@asynccontextmanager
async def lifespan(app: FastAPI):
    SQLModel.metadata.create_all(engine)  # creates db + table on startup

    # add some sample services the first time the db is created
    with Session(engine) as session:
        if not session.exec(select(Service)).first():
            session.add(Service(name="Shipping", service_time=5))
            session.add(Service(name="Accounts", service_time=10))
            session.commit()
    yield


app = FastAPI(lifespan=lifespan)

# ---------- Helpers ----------

def get_counter_404(session: Session, counter_id: int) -> Counter:
    counter = session.get(Counter, counter_id)
    if counter is None:
        raise HTTPException(404, "Counter not found")
    return counter

def check_services_exist(session: Session, ids: list[int]) -> list[int]:
    ids = sorted(set(ids))
    if ids:
        found = session.exec(select(Service.id).where(Service.id.in_(ids))).all()
        if len(found) != len(ids):
            raise HTTPException(422, "Unknown service id in service_ids")
    return ids

def set_counter_services(session: Session, counter_id: int, ids: list[int]) -> None:
    for link in session.exec(select(Counter_Service).where(Counter_Service.counter_id == counter_id)).all():
        session.delete(link)
    session.flush()
    for service_id in ids:
        session.add(Counter_Service(counter_id=counter_id, service_id=service_id))

# ---------- Routes ----------

@app.post("/ticket", response_model=Ticket, status_code=201)
def new_ticket(service_id: int, session: SessionDep):
    service = session.get(Service, service_id)
    if not service:
        raise HTTPException(404, "Service not found")

    ticket = Ticket(service_id=service_id)
    session.add(ticket)
    session.commit()
    session.refresh(ticket)  # loads the generated id
    return ticket

@app.get("/ticket", response_model=Ticket, status_code=201)
def new_ticket(ticket_id: int, session: SessionDep):
    ticket = session.get(Ticket, ticket_id)
    if not ticket:
        raise HTTPException(404, "Ticket not found")
    return ticket

@app.get("/services", response_model=list[Service], status_code=200)
def get_services(session: SessionDep):
    services = session.exec(select(Service)).all()
    return services

@app.post("/services", response_model=Service, status_code=201)
def create_service(service: Service, session: SessionDep):
    db_service = Service.model_validate(service)
    session.add(db_service)
    session.commit()
    session.refresh(db_service)  # loads the generated id
    return db_service

@app.post("/counters", response_model=Counter, status_code=201)
def create_counter(service_ids: list[int], session: SessionDep):
    ids = check_services_exist(session, service_ids)
    counter = Counter()
    session.add(counter)
    session.flush()  # loads the generated id
    set_counter_services(session, counter.id, ids)
    session.commit()
    
@app.get("/counters", response_model=list[Counter], status_code=200)
def get_counters(session: SessionDep):
    counters = session.exec(select(Counter)).all()
    return counters

@app.get("/counters/{counter_id}", response_model=Counter, status_code=200)
def get_counter(counter_id: int, session: SessionDep):
    return get_counter_404(session, counter_id)

@app.put("/counters/{counter_id}", response_model=Counter, status_code=200)
def update_counter(counter_id: int, service_ids: list[int], session: SessionDep):
    counter = get_counter_404(session, counter_id)
    ids = check_services_exist(session, service_ids)
    set_counter_services(session, counter.id, ids)
    session.commit()
    return counter

"""
@app.post("/cars", response_model=Car, status_code=201)
def create_car(car: CarCreate, session: SessionDep):
    db_car = Car.model_validate(car)
    session.add(db_car)
    session.commit()
    session.refresh(db_car)  # loads the generated id
    return db_car


@app.get("/cars", response_model=list[Car])
def list_cars(
    session: SessionDep,
    brand: str | None = None,
    offset: int = 0,
    limit: Annotated[int, Query(le=100)] = 100,
):
    query = select(Car)
    if brand:
        query = query.where(Car.brand == brand)
    return session.exec(query.offset(offset).limit(limit)).all()


@app.get("/cars/{car_id}", response_model=Car)
def get_car(car_id: int, session: SessionDep):
    car = session.get(Car, car_id)
    if not car:
        raise HTTPException(404, "Car not found")
    return car


@app.patch("/cars/{car_id}", response_model=Car)
def update_car(car_id: int, car: CarUpdate, session: SessionDep):
    db_car = session.get(Car, car_id)
    if not db_car:
        raise HTTPException(404, "Car not found")
    db_car.sqlmodel_update(car.model_dump(exclude_unset=True))
    session.add(db_car)
    session.commit()
    session.refresh(db_car)
    return db_car


@app.delete("/cars/{car_id}", status_code=204)
def delete_car(car_id: int, session: SessionDep):
    car = session.get(Car, car_id)
    if not car:
        raise HTTPException(404, "Car not found")
    session.delete(car)
    session.commit()
    """
