from contextlib import asynccontextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Annotated

from fastapi import Depends, FastAPI, HTTPException, Query
from sqlmodel import Field, Session, SQLModel, create_engine, select

# ---------- Models ----------

class Service(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)  # generated by the db
    name: str
    service_time: int  # average minutes per customer

class Ticket(SQLModel, table=True):
    id: int | None = Field(default=None, primary_key=True)  # generated by the db
    service_id: int = Field(foreign_key="service.id")
    status: str = "waiting" # waiting/serving/done
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

# ---------- DB setup ----------

DB_PATH = Path(__file__).resolve().parent.parent / "OQM.db"  # backend/OQM.db

engine = create_engine(
    f"sqlite:///{DB_PATH}",
    connect_args={"check_same_thread": False},  # needed for SQLite + FastAPI
)


def get_session():
    with Session(engine) as session:
        yield session


SessionDep = Annotated[Session, Depends(get_session)]


@asynccontextmanager
async def lifespan(app: FastAPI):
    SQLModel.metadata.create_all(engine)  # creates db + table on startup

    # add some sample services the first time the db is created
    with Session(engine) as session:
        if not session.exec(select(Service)).first():
            session.add(Service(name="Shipping", service_time=5))
            session.add(Service(name="Accounts", service_time=10))
            session.commit()
    yield


app = FastAPI(lifespan=lifespan)


# ---------- Routes ----------

@app.post("/ticket", response_model=Ticket, status_code=201)
def new_ticket(service_id: int, session: SessionDep):
    service = session.get(Service, service_id)
    if not service:
        raise HTTPException(404, "Service not found")

    ticket = Ticket(service_id=service_id)
    session.add(ticket)
    session.commit()
    session.refresh(ticket)  # loads the generated id
    return ticket

@app.get("/ticket", response_model=Ticket, status_code=200)
def get_ticket(ticket_id: int, session: SessionDep):
    ticket = session.get(Ticket, ticket_id)
    if not ticket:
        raise HTTPException(404, "Ticket not found")
    return ticket

@app.get("/services", response_model=list[Service], status_code=200)
def get_services(session: SessionDep):
    services = session.exec(select(Service)).all()
    return services

@app.post("/services", response_model=Service, status_code=201)
def create_service(service: Service, session: SessionDep):
    db_service = Service.model_validate(service)
    session.add(db_service)
    session.commit()
    session.refresh(db_service)  # loads the generated id
    return db_service